FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build-env

WORKDIR /app

COPY . ./
RUN dotnet restore PElementApi/PElementApi.csproj

RUN dotnet publish PElementApi/PElementApi.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "PElementClient.dll"]